---
title: "eds212-day2-tasks-quarto"
format: html
editor: visual
---

#test derivative 
#g(t) = 2.2 + (3.1 * t) - 5.6 * t^4 + (4.3/t^3)


```{r}

library(ggplot2)
library(palmerpenguins)
library(tidyverse)
```

```{r}

fd_ft <- D(expr = expression(2.2 + (3.1 * t) - 5.6 * t ^4 + (4.3/ t ^3)), name = "t")
fd_ft

```

```{r}
fd_fx <- D(expr = expression(x^2), name = "x")
fd_fx
x <- 3
eval(fd_fx)
```


```{r}
pd_pa <- D(expr = expression(2 * ((3 * a + 2) ^4) - 5), name = "a")
a <- 1.2
eval(pd_pa)
```
# Section 4

#storing derivative 

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) + geom_jitter(aes(color = species)) + scale_color_manual(values = c("red","blue","black")) + 
  labs(x = "Bill Length",
       y = "Bill Depth",
       title = "Bill Length vs Bill Depth",
       subtitle = "Antartica (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman") +
  facet_wrap(~island)
theme_minimal
```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + geom_jitter(aes(color = species))
```



